# Generated by Django 5.1 on 2024-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='File_Path'),
        ),
    ]
