# Generated by Django 5.1 on 2024-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_estate_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recentposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=1000000)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('data_aos', models.IntegerField()),
            ],
        ),
    ]
