# Generated by Django 5.1 on 2024-09-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_recentposts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, upload_to='mediaroot'),
        ),
    ]
