# Generated by Django 5.1 on 2024-09-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_estate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='pic',
            field=models.ImageField(upload_to='mediaroot'),
        ),
    ]
