# Generated by Django 5.1 on 2024-10-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_estate_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, upload_to='mediaroot'),
        ),
    ]
