# Generated by Django 5.1 on 2024-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_estate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='mediaroot'),
        ),
    ]
