# Generated by Django 5.1 on 2024-10-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_estate_distance_alter_estate_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='pic',
        ),
    ]
